CREATE DATABASE delilah;
use delilah;
CREATE TABLE usuarios (
  id INT(11) NOT NULL PRIMARY KEY AUTO_INCREMENT,
  idRol INT NOT NULL,
  usuario VARCHAR(45) NOT NULL UNIQUE,  
  password VARCHAR(200) NOT NULL,
  mail VARCHAR(45) NOT NULL UNIQUE,
  nombre VARCHAR(45) NOT NULL,
  apellido VARCHAR(45) NOT NULL,  
  telefono VARCHAR(15) NOT NULL,
  direccion VARCHAR(80) NOT NULL  
  );
   
CREATE TABLE pedidos (
  id INT(11) NOT NULL PRIMARY KEY AUTO_INCREMENT,
  idUsuario INT NOT NULL,  
  idFormaDePago INT NOT NULL,
  idEstado INT NOT NULL,
  precioTotal DECIMAL(7,2),
  hora DATETIME NOT NULL
  );

CREATE TABLE estados (
id INT(11) NOT NULL PRIMARY KEY AUTO_INCREMENT,
descripcion VARCHAR(45) NOT NULL);

CREATE TABLE formasDePago (
id INT(11) NOT NULL PRIMARY KEY AUTO_INCREMENT,
descripcion VARCHAR(45) NOT NULL);

CREATE TABLE renglones (
id INT(11) NOT NULL PRIMARY KEY AUTO_INCREMENT,
idPedido INT NOT NULL,
idProducto INT NOT NULL,
cantidad INT NOT NULL,
precioRenglon DECIMAL(7,2) NOT NULL);

CREATE TABLE productos (
id INT(11) NOT NULL PRIMARY KEY AUTO_INCREMENT,
nombre VARCHAR(60) NOT NULL UNIQUE ,
precioUnitario DECIMAL(7,2) NOT NULL,
urlFoto VARCHAR(200),
disponible BIT(1) NOT NULL);

CREATE TABLE roles(
id INT(11) NOT NULL PRIMARY KEY AUTO_INCREMENT,
descripcion VARCHAR(45) NOT NULL
);

ALTER TABLE renglones
ADD CONSTRAINT FK_RENGLONES_PRODUCTOS
FOREIGN KEY (idProducto) REFERENCES productos(id);

ALTER TABLE renglones
ADD CONSTRAINT FK_RENGLONES_PEDIDOS
FOREIGN KEY (idPedido) REFERENCES pedidos(id);

ALTER TABLE pedidos
ADD CONSTRAINT FK_PEDIDOS_USUARIOS
FOREIGN KEY (idUsuario) REFERENCES usuarios(id);

ALTER TABLE pedidos
ADD CONSTRAINT FK_PEDIDOS_ESTADOS
FOREIGN KEY (idEstado) REFERENCES estados(id);

ALTER TABLE pedidos
ADD CONSTRAINT FK_PEDIDOS_FORMAS_DE_PAGO
FOREIGN KEY (idFormaDePago) REFERENCES formasDePago(id);

ALTER TABLE usuarios
ADD CONSTRAINT FK_USUARIOS_ROLES
FOREIGN KEY (idRol) REFERENCES roles(id);





